# Wait for Bun support perf_hooks.createHistogram (https://github.com/oven-sh/bun/issues/8815)
FROM imbios/bun-node:1-22-slim AS base

RUN apt update && apt install -y procps

WORKDIR /usr/src/app

FROM base AS install

RUN mkdir -p /temp/dev

COPY package.json bun.lockb /temp/dev/

RUN cd /temp/dev && bun install --frozen-lockfile

FROM base AS release

COPY --from=install /temp/dev/node_modules node_modules

COPY . .

EXPOSE 3000/tcp

ENTRYPOINT [ "bun", "run", "start:dev" ]
